# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"



class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        def get_fre(s):
            fre = {}
            for i in s:
                fre[i] = fre.get(i, 0) + 1
            return fre
        s_fre = get_fre(s)
        t_fre = get_fre(t)
        for i in t_fre.keys():
            if s_fre.get(i) != t_fre.get(i):
                return i
        return  
        